### ISSUE TITLE
Problem using gMSA accounts to read LAPS passwords.

### ISSUE THREAD

**Issue by vaiknesiil** [lithnet/laps-web#37]
Hello!

Installed LAPS-WEB and got it to work with regular user based with password service account, but for security reasons we would like to use Group Managed Service Accounts (gMSA).
* IIS Application Pool is working with a gMSA account. 
* OU's and ms-Mcs-AdmPwd, ms-Mcs-AdmPwdExpirationTime have read/write rights for gMSA account, but the web is saying that "The requested computer does not have a LAPS password"

Changing only Application Pool back to regular service account, everything works again.

Is LAPS-WEB capable event to use gMSA accounts?

**Comment by ryannewington** [comment]
Hi @vaiknesiil ,

LAPS web is about to be replaced by Lithnet Access Manager which supports GMSAs out of the box. It does everything LAPS web does and more. I suggest you look to use this instead. I have heard of GMSA issues with IIS app pool accounts, but I haven't looked into exactly the cause here.

https://github.com/lithnet/access-manager/wiki

**Comment by vaiknesiil** [comment]
Just for info.

Setting up Lithnet Access Manager and using those scritps to setup gMSA account fixed my problem with LAPS-WEB.
So at the moment both services are up and running.
